[package]
name = "s5pp"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = "0.3"
