[package]
name = "s5pp"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = "0.3"
